### ISSUE TITLE
Question, why was cmake support removed?

### ISSUE THREAD

**Issue by jeremyong** [ARM-software/optimized-routines#31]
Many toolchains (most notably, the Android NDK but also microcontroller toolchains such as the ESP32) use cmake internally.

Cmake let's you build dependencies transitively in manner that inherits the build settings of the parent project. This is important because if I want to target armv7, vs arm64, I can change one setting at the project root and downstream dependencies (such as this library) will be properly rebuilt in the correct directory. With a make-based toolchain, no build settings are inherited, and the user must manually mange the `config.mk` file or juggle binaries. This makes taking future upstream changes more cumbersome as well. A cmake project also integrates nicely with modules such as `ExternalProject` and/or `FetchContent` so that the build system can automatically fetch this dependency with the requested git tag.

**Comment by nsz-arm** [comment]
the cmake build system was broken and inflexible and using gnu makefiles was the easiest for me to fix it.

it was also important to be able to build the project in build environments where (this right version of) cmake is not available since cmake itself is hard to build and this project is often built in environments that i don't control.

config.mk was designed so it can be generated (maybe even by cmake if you need that), but there are several project specific settings that should be selected manually anyway (so in the end i never got around to write a configure script for it).

direct integration without build system change was not the goal of this project: we may publish half finished code here for whatever reason, that you may decide not to build or use. we upstream code from here to many projects most of which want full control over their build system and have different requirements. we might change things so that it is easier to use this project as a library dependency but that will be significant effort because we would have to commit to stable library API and ABI and build system.

**Comment by jeremyong** [comment]
Thanks for the response
