### ISSUE TITLE
ILP32 is unsupported

### ISSUE THREAD

**Issue by KinseyMoore** [ARM-software/optimized-routines#32]
It appears that the hand-coded assembly in AArch64 strcmp does not sanitize the incoming address parameters in x0 and x1 when compiled for AArch64 ILP32. Based on my reading of the AArch64 Procedure Call Specification and GCC's output for similar function signatures, the callee is responsible for sanitization of the pointer addresses. I encountered this because I have a struct containing a pointer and length returned from another function that happens to get packed into a single register (x0) and GCC passes this unmodified into strcmp as the first argument.

According to the aapcs64: "Any part of a register or a stack slot that is not used for an argument (padding bits) has unspecified content at the callee entry point."

I suspect this is a problem for all the hand-coded AArch64 assembly present in this repository.

**Comment by Wilco1** [comment]
Indeed there is no ILP32 support. Apart from GLIBC, which has experimental ILP32 support on a separate branch, I don't believe there is ILP32 support in any other libraries. It could be fixed of course, however there is very little use of it AFAIK, hence no urgency to add support. What do you use ILP32 for?

That (still beta) ABI choice is unfortunate indeed, it would be better to have the caller ensure the top bits are cleared so that calling assembly code works without requiring changes to support ILP32.

**Comment by KinseyMoore** [comment]
I've been working on AArch64 support in RTEMS to include ILP32. The code here has been included through newlib and I'm currently working around the missing callee-enforced address sanitization by compiling newlib with -DPREFER_SIZE_OVER_SPEED to force use of the C sources instead.

**Comment by KinseyMoore** [comment]
In my case, ILP32 is a very desirable ABI to have available but I understand why it's not used much elsewhere.

**Comment by KinseyMoore** [comment]
Would you be willing to accept a patch for ILP32 compatibility?

**Comment by nsz-arm** [comment]
patch will be accepted. you have to fill in the contribution form. and we expect the asm to look similar to glibc (i.e. use same coding style, don't introduce gratuitous changes to the current code etc)

**Comment by nsz-arm** [comment]
i'm closing this, https://github.com/ARM-software/optimized-routines/commit/afd6244a1f8d92299967d3d50e6f6a1466da413f fixed this.
