### ISSUE TITLE
Memcpy/Memset Implementations with Non-temporal load/stores

### ISSUE THREAD

**Issue by shakan-qcom** [ARM-software/optimized-routines#66]
Hi All,
      We have ARM CPUs which performs best with Non-temporal load/stores (LDNP/STNP) for large buffer copy/memset operations.  Do we have any plans to add memcpy/memset with transient load/store instructions ? Do you recommend pushing a reference implementation to this repo, so that it get reflected in Android bionic?  Thanks in advance, Please provide your suggestion.

**Comment by xboxfanj** [comment]
@Wilco1 Android 14 uses AOR 23.01 memcpy
https://android.googlesource.com/platform/external/arm-optimized-routines/+/refs/heads/android14-qpr1-release/METADATA

https://android.googlesource.com/platform/bionic/+/refs/heads/android14-qpr1-release/libc/arch-arm64/dynamic_function_dispatch.cpp#50

Qualcomm was using https://git.codelinaro.org/clo/la/platform/bionic/-/commit/7a24da08feedebfc4d6b2097cef945aa714d68c5 which is the same as https://android.googlesource.com/platform/bionic/+/2146d142b23b830ad94f8479ce5abeaa15820e7d but that was rebased out in their Android 14 merge, so they are also using AOR 23.01.

**Comment by Wilco1** [comment]
So it looks like Android is now selecting ifunc implementations purely based on architectural features. GLIBC has been moving in that direction for a while to avoid having to maintain string functions for each microarchitecture.

**Comment by xboxfanj** [comment]
That's right @Wilco1.  Android largely has not had microarch-specific string functions on AArch64 (at least compared to Arm32 where every microarch had its own routines).  I'm sure if certain cores did need specific handling to avoid regressions they would merge that.  What are your thoughts on the current state?

If ASIMD use ASIMD memcpy and remove
Else use integer memcpy and memmove

If MTE use MTE functions
Else use standard functions

As far as I can tell this is still mostly optimal on modern cores though I know in the past, integer memcpy outperformed ASIMD on some little cores.  Also, SVE should probably be enabled where present since non-Qualcomm Armv9 SoCs enable it.

**Comment by Wilco1** [comment]
There is no point in checking ASIMD since that is available on all known cores. So Android will always select __memcpy_aarch64_simd (which is a good thing even if it isn't optimal for old little cores).

Adding SVE memcpy/memmove would be useful, but you need a modern Linux kernel for that.
